name: Update Confluence Page

on:
  push:
    paths:
      - 'README.md'

jobs:
  update-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert README.md to HTML
        run: pandoc README.md -f markdown -t html -s -o README.html

      - name: Update Confluence page
        env:
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
        run: |
          # Create the authorization header
          AUTH_HEADER="Authorization: Basic $(echo -n "${CONFLUENCE_USERNAME}:${CONFLUENCE_API_TOKEN}" | base64)"
          
          # Read the HTML content and escape double quotes
          CONTENT=$(cat README.html | sed 's/"/\\"/g')
          
          # Create the JSON payload
          JSON_PAYLOAD=$(jq -n \
            --arg title "Your Page Title" \
            --arg content "$CONTENT" \
            '{version: {number: 2}, title: $title, body: {storage: {value: $content, representation: "storage"}}}')
          
          # Update the Confluence page
          curl -X PUT \
            -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD" \
            https://eagleeyenetworks.atlassian.net/wiki/rest/api/content/${CONFLUENCE_PAGE_ID}

      - name: Clean up
        run: rm -f README.html
